# -*- coding: utf-8 -*-
"""CS3793_5233_assignment1_xpn197TURNIN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktYZoiFdU7f7OUUz5EEZ-4-7vKrMe3fz

# UTSA CS 3793/5233: Assignment-1

**Torres - Jose - (xpn197)**

## Learning Objectives


*   Read data from a file and Create a graph
*   Implement Uninformed & Informed searching strategies
*   Apply different searching strategies for the given problem
*   Analyze and Compare the searching strategies

## Description

This assignment is focused on **python file reading, graph creation** and implementation of **search algorithms**. 
In the following sections, you will complete a series of tasks for a made up problem of *Coronavirus in Texas*.

*   Coronavirus is non-discriminatory, in the sense that it can spread from one city to any other city. The only goal of the virus is to spread to all cities in Texas. Find a possible way for the virus to spread (Uninformed Search).
*   To counter the effect of the virus, vaccine needs to be distributed to all cities. One city has more demand than supply, whereas one city has a shortage of vaccines. The goal is to find an **optimal** strategy to transport the vaccine (Informed Search) from the city with high supply (low demand) to the city with low supply (high demand).

The base structure and comments are provided on what should be done. You can use some libraries that help support you for the successful completion of the assignment. However, you **CANNOT** use a complete library for the search algorithms. You can get pieces of code from online, but please cite the source properly.

#Reading Data Files & Creating a 2D Graph

##(45 points)

In this section, you will write code to read the data files provided, cities.csv and distances.csv, and create a 2D graph consisting of nodes and edges. The goal is to use this graph for the 2 search agents that you will create in the next section.

Provided with this lab, on Blackboard, you will find 2 csv files:

*   **cities.csv** - This file contains a list of coordinates for selected cities in Texas, in the following format:
```
San Antonio,29.4685,-98.5254
```
The above line means that San Antonio is located at the latitude and longitude of 29.4685 N and 98.5254 W respectively. Note that the '-ve' sign denotes 'S' for latitude and 'W' for longitude. While performing calculations you will need to ignore the sign.

*   **distances.csv** - This file contains distance values between two cities of Texas, if a path exists, in the following format:
```
San Antonio,New Braunfels,30.80876734
```
The above line denotes that there should be an edge between *San Antonio* and *New Braunfels* and the weight on that edge, i.e. the distance, is *30.80876734*.

In the code blocks below, handle the logic for the graph. Load the graph data from the give files and display a 2D graph of the given data, with labeled nodes and edges. Create as many functions or code blocks as needed.

##Extra Credit (4 points)

Overlay the 2D graph on an image of the Texas state map.
"""

import csv
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import queue
from queue import PriorityQueue
import geopy.distance

citiesData = pd.read_csv("cities.csv", header = None)
longitudes = citiesData[2]
latitudes = citiesData[1]
cities = citiesData[0]

distancesData = pd.read_csv("distances.csv", header = None)
firstCity = distancesData[0]
secondCity = distancesData[1]
distances = distancesData[2]

straightlineDist = []

for x in range(len(cities)):
  cord_1 = (latitudes[x], longitudes[x])
  cord_2 = (30.5852, -96.296)
  straightlineDist.append(geopy.distance.vincenty(cord_1, cord_2).miles)

# Display a 2D graph of the given data.

G = nx.Graph()
for i in range(len(citiesData)):
  G.add_node(cities[i], name = cities[i], pos = (longitudes[i], latitudes[i]))

for i in range(len(distancesData)):
  G.add_edge(firstCity[i], secondCity[i], weight = distances[i])


elarge = [(u,v) for (u, v, d) in G.edges(data = True) if d["weight"] > 0.5]
esmall = [(u,v) for (u, v, d) in G.edges(data = True) if d["weight"] <= 0.5]

pos = nx.get_node_attributes(G, 'pos')


nx.draw_networkx_nodes(G, pos, node_size = 10)
nx.draw_networkx_edges(G, pos, edgelist = elarge, width = 2)
nx.draw_networkx_edges(G, pos, edgelist = esmall, width = 2, alpha = 0.5, edge_color = "b", style = "dashed")

nx.draw_networkx_labels(G, pos, font_size = 8, font_family = "sans-serif")


ax = plt.gca()
ax.margins(0.009)

plt.axis("off")
plt.tight_layout()
plt.show()

"""#Virus Spread - Uninformed Search Agent

##(40 points)

In this section, you will use the graph created in the previous section and create an *uninformed search* agent that will print the path how the virus will spread to all the provided Texas cities. The first confirmed case of the virus was in **Three Rivers** and starts spreading from there. The virus does not discriminate and it needs to spread to all the cities of Texas.

In the following code block, write code to implement **any** uninformed search strategy. You are free to create more code blocks if needed. As the output, print

*   The path or sequence of cities that will be infected by the spread of Coronavirus.
*   The distance travelled by the selected virus spreading strategy.

##Extra Credit (3 points)
On the 2D graph and the Texas state map, overlay the selected path along with the cities visited.
"""

explored = []
queue = []

def BFS(exp, graph, node):
  exp.append(node)
  queue.append(node)
  global distanceTrav
  

  while queue:
    popped = queue.pop(0)
    for edge in graph[popped]:
      if edge not in exp:
        exp.append(edge)
        queue.append(edge)
        distanceTrav += graph.get_edge_data(popped, edge)["weight"]

distanceTrav = 0.0
BFS(explored, G, 'Three Rivers')
print("BFS\nVirus Spread Path:")
for x in range(len(explored)):
  print(x, ".", explored[x])
print("Total Distance Travelled =", distanceTrav)

"""#Vaccine Transportation - Informed Search Agent

##(40 points)

In this section, you will create an *informed search* agent that will be used to transport the vaccine. The city of **San Antonio** has more supply of vaccine than the demand. The goal is to create an **optimal strategy** to transport the vaccine and make it available at the highly affected city of **College Station**, where there is a shortage of vaccines.

In the following code block, write code to implement an **optimal** informed search strategy. You are free to create more code blocks if needed. As the output, print 

*   The path / sequence of cities that will be visited in the optimal vaccine transportation strategy.
*   The total distance travelled in the optimal vaccine transportation strategy.


##Extra Credit (3 points)
On the 2D graph and the Texas state map, overlay the selected path along with the cities visited.
"""

def QIn(node, queue):
  for x in range(len(queue)):
    if queue[x] == node:
      return x

def findIn(node):
  for x in range(len(cities)):
    if cities[x] == node:
      return x

def GBFS(graph, startNode, goalNode):
  explored = []
  edges = []
  edges.append(startNode)
  popped = edges.pop(0)
  explored.append(popped)
  qIn = 0
  global totalDistance 
  for edge in graph[startNode]:
    if edge not in edges:
      edges.append(edge)

  while edges:
    minStr = straightlineDist[findIn(edges[0])]
    for x in range(len(edges)):
      ind = findIn(edges[x])
      curr = straightlineDist[ind]
      if curr < minStr:
        minStr = curr
        qIn = QIn(edges[x], edges)
        #popped = edges[x]
    popped = edges.pop(qIn)
    totalDistance += graph.get_edge_data(explored[-1], popped)["weight"]
    if popped == goalNode:
      explored.append(popped)
      return explored
    explored.append(popped)

    for edge in graph[popped]:
      if edge not in edges:
        edges.append(edge)
      
    
totalDistance = 0.0
result = GBFS(G, "San Antonio", "College Station")
print("GBFS\nNodes Visited -")
for x in range(len(result)):
  print(" ", result[x])
print("Vaccine Distribution Path:")
for x in range(len(result)):
  print(x, ".", result[x])
print("Total Distance Traveled: ", totalDistance)

"""#Submission Instructions

1.   Complete all tasks above - **File MUST contain the output for ALL cells**
2.   Export this notebook as .ipynb
      (File > Download as ipynb)
3.   Upload the .ipynb file on Blackboard

##Rubric

*   (45 points) Reading Data files & Creating a 2D Graph
*   (40 points) Virus Spread - Uninformed Search Agent
*   (40 points) Vaccine Transportation - Informed Search Agent
*   (10 points) Extra Credit - on the Texas map image, overlay the 2D graph and the paths selected by the search agents
"""